import type { Product, Order } from './types'

export const sampleProducts: Product[] = [
  {
    id: '1',
    title: 'Wireless Bluetooth Earbuds TWS 5.0 Headphones',
    description: 'High-quality wireless earbuds with active noise cancellation, 30-hour battery life, and IPX5 water resistance. Perfect for sports, travel, and daily use.',
    price: 12.50,
    originalPrice: 8.20,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1598331668826-20cecc596b86?w=400&h=400&fit=crop',
    ],
    category: 'Electronics',
    supplier: 'Shenzhen Audio Tech Co., Ltd',
    minOrder: 50,
    shippingTime: '15-25 days',
    shippingCost: 2.50,
    shippingMethods: [
      { id: 'sm1', name: 'ePacket', cost: 2.50, estimatedDays: '15-25', carrier: 'China Post' },
      { id: 'sm2', name: 'DHL Express', cost: 12.00, estimatedDays: '5-8', carrier: 'DHL' },
    ],
    weight: '0.15 kg',
    dimensions: '8x6x4 cm',
    sku: 'TWS-BT50-001',
    tags: ['earbuds', 'wireless', 'bluetooth', 'audio'],
    rating: 4.8,
    reviews: 2341,
    variants: [
      { id: 'v1', name: 'Color', options: ['Black', 'White', 'Blue'], price: 8.20, sku: 'TWS-BLK', inventory: 500 },
    ],
    status: 'draft',
    alibabaUrl: 'https://alibaba.com/product/123',
    source: 'alibaba',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    title: 'Smart Watch Fitness Tracker with Heart Rate Monitor',
    description: 'Advanced smartwatch with comprehensive health tracking, 1.4" AMOLED display, GPS, and 7-day battery life. Compatible with iOS and Android.',
    price: 24.99,
    originalPrice: 15.80,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1434493789847-2a75b0eb9b96?w=400&h=400&fit=crop',
    ],
    category: 'Electronics',
    supplier: 'Guangzhou Smart Devices Ltd',
    minOrder: 30,
    shippingTime: '12-20 days',
    shippingCost: 3.00,
    shippingMethods: [
      { id: 'sm1', name: 'Standard Shipping', cost: 3.00, estimatedDays: '12-20', carrier: 'YunExpress' },
      { id: 'sm2', name: 'Express Shipping', cost: 15.00, estimatedDays: '4-7', carrier: 'FedEx' },
    ],
    weight: '0.25 kg',
    dimensions: '12x10x5 cm',
    sku: 'SW-FIT-002',
    tags: ['smartwatch', 'fitness', 'health', 'tracker'],
    rating: 4.6,
    reviews: 1893,
    variants: [
      { id: 'v1', name: 'Color', options: ['Black', 'Silver', 'Rose Gold'], price: 15.80, sku: 'SW-BLK', inventory: 300 },
      { id: 'v2', name: 'Size', options: ['40mm', '44mm'], price: 15.80, sku: 'SW-40', inventory: 200 },
    ],
    status: 'ready',
    alibabaUrl: 'https://alibaba.com/product/456',
    source: 'alibaba',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    title: 'Portable Power Bank 20000mAh Fast Charging',
    description: 'High-capacity power bank with 22.5W fast charging, dual USB-C ports, LED display, and compact design. Charge 3 devices simultaneously.',
    price: 18.99,
    originalPrice: 11.50,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop',
    ],
    category: 'Electronics',
    supplier: 'Dongguan Power Solutions',
    minOrder: 100,
    shippingTime: '10-18 days',
    shippingCost: 4.50,
    shippingMethods: [
      { id: 'sm1', name: 'ePacket', cost: 4.50, estimatedDays: '10-18', carrier: 'China Post' },
      { id: 'sm2', name: 'UPS Express', cost: 18.00, estimatedDays: '3-5', carrier: 'UPS' },
    ],
    weight: '0.45 kg',
    dimensions: '15x8x3 cm',
    sku: 'PB-20K-003',
    tags: ['powerbank', 'charging', 'portable', 'battery'],
    rating: 4.9,
    reviews: 5621,
    variants: [
      { id: 'v1', name: 'Color', options: ['Black', 'White'], price: 11.50, sku: 'PB-BLK', inventory: 800 },
      { id: 'v2', name: 'Capacity', options: ['10000mAh', '20000mAh'], price: 11.50, sku: 'PB-10K', inventory: 400 },
    ],
    status: 'published',
    alibabaUrl: 'https://alibaba.com/product/789',
    source: 'alibaba',
    shopifyId: 'gid://shopify/Product/123456',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    title: 'LED Ring Light 10" with Tripod Stand',
    description: 'Professional ring light for streaming, video calls, and content creation. 3 color modes, 10 brightness levels, phone holder included.',
    price: 15.99,
    originalPrice: 9.20,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=400&fit=crop',
    ],
    category: 'Photography',
    supplier: 'Yiwu Lighting Equipment Co.',
    minOrder: 20,
    shippingTime: '8-15 days',
    shippingCost: 5.00,
    shippingMethods: [
      { id: 'sm1', name: 'Standard', cost: 5.00, estimatedDays: '8-15', carrier: 'Cainiao' },
      { id: 'sm2', name: 'DHL Express', cost: 20.00, estimatedDays: '3-5', carrier: 'DHL' },
    ],
    weight: '1.2 kg',
    dimensions: '30x30x10 cm',
    sku: 'RL-10IN-004',
    tags: ['ringlight', 'photography', 'streaming', 'lighting'],
    rating: 4.7,
    reviews: 892,
    variants: [
      { id: 'v1', name: 'Size', options: ['10 inch', '12 inch', '18 inch'], price: 9.20, sku: 'RL-10', inventory: 150 },
    ],
    status: 'draft',
    alibabaUrl: 'https://alibaba.com/product/101',
    source: 'alibaba',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    title: 'Yoga Mat Non-Slip Eco-Friendly 6mm',
    description: 'Premium TPE yoga mat with alignment lines, carrying strap, and double-sided texture. Perfect for yoga, pilates, and home workouts.',
    price: 22.50,
    originalPrice: 14.00,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop',
    ],
    category: 'Sports',
    supplier: 'Ningbo Fitness Gear Co.',
    minOrder: 50,
    shippingTime: '15-25 days',
    shippingCost: 6.00,
    shippingMethods: [
      { id: 'sm1', name: 'Sea Freight', cost: 6.00, estimatedDays: '20-35', carrier: 'ZTO Express' },
      { id: 'sm2', name: 'Air Express', cost: 25.00, estimatedDays: '5-8', carrier: 'FedEx' },
    ],
    weight: '1.8 kg',
    dimensions: '61x183x0.6 cm',
    sku: 'YM-ECO-005',
    tags: ['yoga', 'fitness', 'mat', 'eco-friendly'],
    rating: 4.5,
    reviews: 1234,
    variants: [
      { id: 'v1', name: 'Color', options: ['Purple', 'Blue', 'Green', 'Pink'], price: 14.00, sku: 'YM-PUR', inventory: 600 },
      { id: 'v2', name: 'Thickness', options: ['4mm', '6mm', '8mm'], price: 14.00, sku: 'YM-4MM', inventory: 300 },
    ],
    status: 'ready',
    alibabaUrl: 'https://alibaba.com/product/202',
    source: 'alibaba',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const sampleOrders: Order[] = [
  {
    id: 'ord-001',
    shopifyOrderId: '#SH-1001',
    orderNumber: 'ORD-2026-001',
    customer: {
      name: 'Carlos Martinez',
      email: 'carlos@example.com',
      phone: '+1 555-0123',
      address: '123 Main St',
      city: 'Miami',
      state: 'FL',
      zip: '33101',
      country: 'US',
    },
    items: [
      { productId: '3', title: 'Portable Power Bank 20000mAh Fast Charging', image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop', quantity: 2, price: 18.99, variant: 'Black / 20000mAh', sku: 'PB-20K-003' },
    ],
    shippingMethod: 'ePacket',
    shippingCost: 4.50,
    shippingStatus: 'shipped',
    trackingNumber: 'EP123456789CN',
    subtotal: 37.98,
    totalPrice: 42.48,
    status: 'fulfilled',
    mode: 'auto',
    createdAt: new Date(Date.now() - 5 * 86400000),
    updatedAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    id: 'ord-002',
    shopifyOrderId: '#SH-1002',
    orderNumber: 'ORD-2026-002',
    customer: {
      name: 'Emily Johnson',
      email: 'emily@example.com',
      address: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zip: '90001',
      country: 'US',
    },
    items: [
      { productId: '1', title: 'Wireless Bluetooth Earbuds TWS 5.0 Headphones', image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop', quantity: 1, price: 12.50, variant: 'White', sku: 'TWS-BT50-001' },
      { productId: '2', title: 'Smart Watch Fitness Tracker', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop', quantity: 1, price: 24.99, variant: 'Black / 44mm', sku: 'SW-FIT-002' },
    ],
    shippingMethod: 'DHL Express',
    shippingCost: 12.00,
    shippingStatus: 'processing',
    subtotal: 37.49,
    totalPrice: 49.49,
    status: 'confirmed',
    mode: 'manual',
    createdAt: new Date(Date.now() - 2 * 86400000),
    updatedAt: new Date(Date.now() - 1 * 86400000),
  },
  {
    id: 'ord-003',
    shopifyOrderId: '#SH-1003',
    orderNumber: 'ORD-2026-003',
    customer: {
      name: 'David Lee',
      email: 'david@example.com',
      address: '789 Pine Rd',
      city: 'New York',
      state: 'NY',
      zip: '10001',
      country: 'US',
    },
    items: [
      { productId: '4', title: 'LED Ring Light 10" with Tripod Stand', image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=400&fit=crop', quantity: 1, price: 15.99, variant: '12 inch', sku: 'RL-10IN-004' },
    ],
    shippingMethod: 'Standard',
    shippingCost: 5.00,
    shippingStatus: 'pending',
    subtotal: 15.99,
    totalPrice: 20.99,
    status: 'pending',
    mode: 'auto',
    notes: 'Customer requested gift wrapping',
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(Date.now() - 86400000),
  },
]
